### ISSUE TITLE
Social media logo cant be loaded

### ISSUE THREAD

**Issue by haikalpe123** [ziofat/material_design_icons_flutter#4] opened 2019-01-17 09:09 UTC
i'm using _MdiIcons.twitter,_ facebook and instagram logo. But none of them can't be loaded. why? is it not updated yet? 
![screenshot_1547715941](https://user-images.githubusercontent.com/43090718/51307411-363be680-1a72-11e9-9ee6-d43db687bbc5.png)

**Comment by StefanLobbenmeier** [comment] 2019-03-19 14:23
I am facing a similar issue, e.g. 

        MdiIcons.fire;

displays as this X symbol as well.

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.14393], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [!] Android Studio (not installed)
> [√] IntelliJ IDEA Ultimate Edition (version 2018.3)
> [!] VS Code, 64-bit edition (version 1.32.3)
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> [√] Connected device (1 available)
> 
> ! Doctor found issues in 2 categories.
> 

I will try to reproduce in a sample project now.

**Comment by StefanLobbenmeier** [comment] 2019-03-19 14:28
I created a sample project and it worked flawlessly... not sure what the issue might be.

**Comment by StefanLobbenmeier** [comment] 2019-03-19 14:32
I ended up solving it on the app where I faced the issue by rebuilding from scratch (with gradle rebuild). Hot reload does not work (probably because some resources have to be transmitted). I think @ziofat can just add this to the readme and close the issue, since @haikalpe123 did not respond anyway.

**Comment by ziofat** [comment] 2019-05-21 13:44
Closed.

**Closed by ziofat** 2019-05-21 13:44 UTC
